language: groovy
jdk:
- oraclejdk8

notifications:
  email:
    on_success: always
    on_failure: always

deploy:
  provider: heroku
  app: nettool
  jdk: oraclejdk8
  strategy: git
  api_key:
    secure: JiU0Cikjz3lYeST+8mqrpST/Mhkr9+NyfSmCqbj2ROTl/4oazTazeWv5eqNJaB3ECZSgQ0h/zsjiuw66kVHo15B3Ye4mJKTTkBpJ3DGGaIO3rDSehDKoGRlk3FAXi+rnJGcq2onhUVyzEIk/UzCmcjnRmOUX3xgLnXZjDXG8C44=
