# IDENTITY (ContextIdApplicationContextInitializer)
spring:
  application:
    name: nettools
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8080
  session-timeout: 30
  tomcat.basedir: /tmp
  tomcat.background-processor-delay: 30
  tomcat.max-threads:  1
  tomcat.uri-encoding:  UTF-8

# SPRING MVC (HttpMapperProperties)
http.mappers.json-pretty-print: true
http.mappers.json-sort-keys: true
spring.mvc.locale: pl_PL
spring.mvc.date-format: dd/MM/yyyy HH:mm:ss



