# IDENTITY (ContextIdApplicationContextInitializer)
spring:
  application:
    name: nettools
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  mvc:
    locale: pl_PL

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8080
  session-timeout: 30
    basedir: /tmp
    background-processor-delay: 30
    max-threads:  1
    uri-encoding:  UTF-8

# SPRING MVC (HttpMapperProperties)
http:
  mappers:
    json-pretty-print: true
    json-sort-keys: true

