# IDENTITY (ContextIdApplicationContextInitializer)
spring:
  application:
    name: nettools
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  mvc:
    locale: pl_PL

nettool.admin.host: nettool.herokuapp.com
